package com.unleashyouradventure.swapi.retriever;

public class BookCategoryRetriever {

    private final static BookCategory cat1;

    static {
        // Generated start
        cat1 = new BookCategory(1, "All");
        BookCategory cat3 = new BookCategory(3, "Fiction");
        cat1.addChild(cat3);
        BookCategory cat892 = new BookCategory(892, "Adventure");
        cat3.addChild(cat892);
        BookCategory cat1248 = new BookCategory(1248, "African American fiction");
        cat3.addChild(cat1248);
        BookCategory cat62 = new BookCategory(62, "Anthologies");
        cat3.addChild(cat62);
        BookCategory cat61 = new BookCategory(61, "Children’s books");
        cat3.addChild(cat61);
        BookCategory cat1223 = new BookCategory(1223, "Christian");
        cat3.addChild(cat1223);
        BookCategory cat1348 = new BookCategory(1348, "Classics");
        cat3.addChild(cat1348);
        BookCategory cat1332 = new BookCategory(1332, "Cultural & ethnic themes");
        cat3.addChild(cat1332);
        BookCategory cat60 = new BookCategory(60, "Drama");
        cat3.addChild(cat60);
        BookCategory cat1206 = new BookCategory(1206, "Fantasy");
        cat3.addChild(cat1206);
        BookCategory cat886 = new BookCategory(886, "Gay & lesbian fiction");
        cat3.addChild(cat886);
        BookCategory cat58 = new BookCategory(58, "Graphic novels & comics");
        cat3.addChild(cat58);
        BookCategory cat884 = new BookCategory(884, "Historical");
        cat3.addChild(cat884);
        BookCategory cat1067 = new BookCategory(1067, "Holiday");
        cat3.addChild(cat1067);
        BookCategory cat883 = new BookCategory(883, "Horror");
        cat3.addChild(cat883);
        BookCategory cat882 = new BookCategory(882, "Humor & comedy");
        cat3.addChild(cat882);
        BookCategory cat1527 = new BookCategory(1527, "Inspirational");
        cat3.addChild(cat1527);
        BookCategory cat4815 = new BookCategory(4815, "Literary collections");
        cat3.addChild(cat4815);
        BookCategory cat57 = new BookCategory(57, "Literature");
        cat3.addChild(cat57);
        BookCategory cat1350 = new BookCategory(1350, "Mashups");
        cat3.addChild(cat1350);
        BookCategory cat879 = new BookCategory(879, "Mystery & detective");
        cat3.addChild(cat879);
        BookCategory cat56 = new BookCategory(56, "Poetry");
        cat3.addChild(cat56);
        BookCategory cat1235 = new BookCategory(1235, "Romance");
        cat3.addChild(cat1235);
        BookCategory cat1213 = new BookCategory(1213, "Science fiction");
        cat3.addChild(cat1213);
        BookCategory cat1337 = new BookCategory(1337, "Themes & motifs");
        cat3.addChild(cat1337);
        BookCategory cat874 = new BookCategory(874, "Thriller & suspense");
        cat3.addChild(cat874);
        BookCategory cat870 = new BookCategory(870, "Women's fiction");
        cat3.addChild(cat870);
        BookCategory cat1018 = new BookCategory(1018, "Young adult or teen");
        cat3.addChild(cat1018);
        BookCategory cat4 = new BookCategory(4, "Non-Fiction");
        cat1.addChild(cat4);
        BookCategory cat96 = new BookCategory(96, "Antiques & Collectibles");
        cat4.addChild(cat96);
        BookCategory cat95 = new BookCategory(95, "Art, Architecture, Photography");
        cat4.addChild(cat95);
        BookCategory cat94 = new BookCategory(94, "Biography");
        cat4.addChild(cat94);
        BookCategory cat93 = new BookCategory(93, "Business & Economics");
        cat4.addChild(cat93);
        BookCategory cat92 = new BookCategory(92, "Career Guides");
        cat4.addChild(cat92);
        BookCategory cat91 = new BookCategory(91, "Children's Books");
        cat4.addChild(cat91);
        BookCategory cat4856 = new BookCategory(4856, "Comics (nonfictional)");
        cat4.addChild(cat4856);
        BookCategory cat90 = new BookCategory(90, "Computers and Internet");
        cat4.addChild(cat90);
        BookCategory cat89 = new BookCategory(89, "Cooking, Food, Wine, Spirits");
        cat4.addChild(cat89);
        BookCategory cat88 = new BookCategory(88, "Education and Study Guides");
        cat4.addChild(cat88);
        BookCategory cat2369 = new BookCategory(2369, "Engineering, trades, and technology");
        cat4.addChild(cat2369);
        BookCategory cat87 = new BookCategory(87, "Entertainment");
        cat4.addChild(cat87);
        BookCategory cat86 = new BookCategory(86, "Gay and Lesbian");
        cat4.addChild(cat86);
        BookCategory cat4816 = new BookCategory(4816, "General reference");
        cat4.addChild(cat4816);
        BookCategory cat85 = new BookCategory(85, "Health, wellbeing, & medicine");
        cat4.addChild(cat85);
        BookCategory cat84 = new BookCategory(84, "History");
        cat4.addChild(cat84);
        BookCategory cat83 = new BookCategory(83, "Home and Garden");
        cat4.addChild(cat83);
        BookCategory cat82 = new BookCategory(82, "Inspiration");
        cat4.addChild(cat82);
        BookCategory cat81 = new BookCategory(81, "Language Instruction");
        cat4.addChild(cat81);
        BookCategory cat80 = new BookCategory(80, "Law");
        cat4.addChild(cat80);
        BookCategory cat79 = new BookCategory(79, "Music");
        cat4.addChild(cat79);
        BookCategory cat78 = new BookCategory(78, "New Age");
        cat4.addChild(cat78);
        BookCategory cat77 = new BookCategory(77, "Parenting");
        cat4.addChild(cat77);
        BookCategory cat76 = new BookCategory(76, "Philosophy");
        cat4.addChild(cat76);
        BookCategory cat75 = new BookCategory(75, "Politics and Current Affairs");
        cat4.addChild(cat75);
        BookCategory cat74 = new BookCategory(74, "Psychology");
        cat4.addChild(cat74);
        BookCategory cat1044 = new BookCategory(1044, "Publishing");
        cat4.addChild(cat1044);
        BookCategory cat73 = new BookCategory(73, "Reference");
        cat4.addChild(cat73);
        BookCategory cat72 = new BookCategory(72, "Relationships and Family");
        cat4.addChild(cat72);
        BookCategory cat71 = new BookCategory(71, "Religion and Spirituality");
        cat4.addChild(cat71);
        BookCategory cat70 = new BookCategory(70, "Science and Nature");
        cat4.addChild(cat70);
        BookCategory cat69 = new BookCategory(69, "Self-improvement");
        cat4.addChild(cat69);
        BookCategory cat68 = new BookCategory(68, "Sex and Relationships");
        cat4.addChild(cat68);
        BookCategory cat67 = new BookCategory(67, "Social Science");
        cat4.addChild(cat67);
        BookCategory cat66 = new BookCategory(66, "Sports & outdoor recreation");
        cat4.addChild(cat66);
        BookCategory cat65 = new BookCategory(65, "Transportation");
        cat4.addChild(cat65);
        BookCategory cat64 = new BookCategory(64, "Travel");
        cat4.addChild(cat64);
        BookCategory cat1049 = new BookCategory(1049, "True Crime");
        cat4.addChild(cat1049);
        BookCategory cat63 = new BookCategory(63, "Weddings");
        cat4.addChild(cat63);

        // Generated end
    }

    public static BookCategory getRootCategory() {
        return cat1;
    }

}
